# Generated by Django 4.2.6 on 2023-10-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Categoria usuario')),
                ('description', models.TextField(default='Nuevo Acceso', verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Categoria usuario',
                'verbose_name_plural': 'Categorias usuarios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='usuario')),
                ('rol', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('avatar', models.ImageField(default='media/users-default.jpg', upload_to='media/')),
            ],
        ),
    ]
