# Generated by Django 4.2.6 on 2023-10-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la cancha (ej cancha1)', max_length=50, verbose_name='cancha')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
            },
        ),
        migrations.CreateModel(
            name='CategoriaCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='CategoriaCancha')),
                ('img_cancha', models.ImageField(blank=True, null=True, upload_to='canchas', verbose_name='Imgcancha')),
                ('categoria', models.CharField(choices=[(1, 'Fútbol'), (2, 'Rugby'), (3, 'Béisbol'), (4, 'Hockey'), (5, 'Voley'), (6, 'Tenis')], max_length=1)),
            ],
            options={
                'verbose_name': 'CategoriaCancha',
                'verbose_name_plural': 'CategoriasCanchas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Cliente')),
                ('teléfono_celular', models.IntegerField(verbose_name='Celular')),
                ('correo_electrónico', models.EmailField(max_length=254)),
                ('socio', models.CharField(choices=[('S1', 'Mienbros Asociados'), ('S2', 'Mienbros Afiliado'), ('S3', 'Mienbros Social')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Reserva')),
                ('estado', models.CharField(choices=[(1, 'Reservado'), (2, 'Confirmado'), (3, 'Cancelado')], max_length=1)),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cancha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.cancha', verbose_name='Cancha')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.AddField(
            model_name='cancha',
            name='cancha_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.categoriacancha', verbose_name='CategoriaCancha'),
        ),
    ]
